apiVersion: v1

kind: ReplicationController

metadata:
  name: kube-demo

spec:
  replicas: 1

  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: kube-demo

  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: kube-demo

    spec:
      volumes:
      - name: config
        secret:
          secretName: config

      containers:
      - name: kube-demo
        image: <image url>
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/kube-demo
          readOnly: true
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
