apiVersion: v1
kind: Service
metadata:
  name: kube-demo
  labels:
    app: kube-demo
spec:
  type: LoadBalancer
  selector:
    app: kube-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
